### ISSUE TITLE
Node names no longer update to country and number

### ISSUE THREAD

**Issue by 1110000111** [snakem982/Pandora-Box#22]
Hello,
In the last few versions of the program, nodes no longer update their names to the country and a number. This was a very useful feature, as it made  categorizing nodes much easier.
Would it be possible to bring this feature back to the program?

Thank you!

**Comment by snakem982** [comment]
Thanks for your feedback,

Because the country region of the node rename is inaccurate, this feature has been removed
You can use the crawl page to manage subscriptions and nodes, and after crawling, use the filter page to organize the profiles by protocol type and country region of the node

I hope it helps you.

1.Crawl
<img width="1186" alt="crawl" src="https://github.com/user-attachments/assets/6fb7f248-33d3-40f8-970e-5e56ccac1e44" />

2.Node Filter
<img width="868" alt="filter" src="https://github.com/user-attachments/assets/85dca9b6-8e48-48b1-9ea4-b24624e08899" />

**Comment by snakem982** [comment]
> I have another issue: the crawler does not work for Sing-Box configurations at all.

That was a bug. It has been fixed in the preview version.
https://github.com/snakem982/Pandora-Box/releases/tag/Prerelease-main

**Comment by snakem982** [comment]
> still not working for me

That might be your network problem.
I tested it and it's fine.
<img width="948" alt="crawl" src="https://github.com/user-attachments/assets/50efb41a-c434-485f-8906-0416c5af81b6" />
<img width="849" alt="crawl" src="https://github.com/user-attachments/assets/1e2026bc-861a-44e7-9889-b8b5eb080560" />
